---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hello-k8s
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: hello-k8s
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-hello-k8s
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: hello-k8s
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "hello-k8s-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: hello-k8s-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-hello-k8s
              servicePort: 8080
